### ISSUE TITLE
Removed from Firefox store

### ISSUE THREAD

**Issue by gundruke** [sidbelbase/undistracted-me#26]
Hello,
The extension seems to be removed from the Firefox store for some reason. Today all of a sudden I saw the background wasn't loading, so, I wanted to reload but it doesn't appear to be in the Firefox store anymore? 

I did try the direct link (https://addons.mozilla.org/en-US/firefox/addon/undistracted-me/) as well. 

Is there any problem?

**Comment by sidbelbase** [comment]
Sorry for the delayed response, firefox removed this extension due to their new policy. They sent me an email to follow the requirements specified in their new policy, but due to lack of time, I couldn't get back to them. As of writing this, I have issued a newer version. I'll let you know when it will be publicly available in the store.

**Comment by sidbelbase** [comment]
Thank you guys for waiting, [the extension is in the store now](https://addons.mozilla.org/en-US/firefox/addon/undistracted-me/). After several attempts, the AMO admins approved my build. I have updated the logo with a new one. Hope you guys haven't moved to other alternatives ;)

I'm closing this issue for now.
